services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - ./:/app/
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      DATABASE_URL: mysql://silverberry:keloglan@db/silverberry
      GOOGLE_CLIENT_ID: 406495185728-bkfgsge8c7sig44avm7jspjq0js4lt0q.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      SESSION_SECRET: p7UpqbYolqRRkXD4QExhdLEpA5SGMXcillhLpL70mIk6sQVnjEKKHxXaMl0Q2gkz
      PORT: 8000
    container_name: silverberry-app

  db:
    image: mariadb:10.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./seed:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "keloglan"
      MYSQL_DATABASE: "silverberry"
      MYSQL_USER: "silverberry"
      MYSQL_PASSWORD: "keloglan"
    container_name: silverberry-db
networks:
  backend:
