"use strict";
const express_1 = require("express");
const authentication_middlewares_1 = require("../middlewares/authentication.middlewares");
const admin_controllers_1 = require("../middlewares/admin.controllers");
const global_middlewares_1 = require("../middlewares/global.middlewares");
const router = (0, express_1.Router)();
router.use(authentication_middlewares_1.checkSession);
router.get('/', admin_controllers_1.homeController);
router.get('/products', global_middlewares_1.populatePagination, admin_controllers_1.listProductsController);
router.get('/products/create', global_middlewares_1.walmartLookupById, admin_controllers_1.createProductController);
router.post('/products/create', admin_controllers_1.saveProductController);
router.get('/products/:id', admin_controllers_1.homeController);
router.get('/sales', admin_controllers_1.salesController);
router.get('/manifests', admin_controllers_1.manifestsController);
router.get('/posts', admin_controllers_1.postsController);
router.get('/workers', admin_controllers_1.workersController);
router.get('/settings', admin_controllers_1.settingsController);
router.get("/walmart-lookup", global_middlewares_1.populatePagination, global_middlewares_1.walmartLookupByQuery, admin_controllers_1.walmartLookupController);
module.exports = router;
